/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

int *add_1_svc(numbers *argp, struct svc_req *rqstp){
	static int result;
	printf("Funcao soma(%d, %d) foi chamada\n", argp->a, argp->b);
	result = argp->a + argp->b;
	return &result;
}

int *sub_1_svc(numbers *argp, struct svc_req *rqstp){
static int result;
	printf("Funcao subtracao(%d, %d) foi chamada\n", argp->a, argp->b);
	result = argp->a - argp->b;
	return &result;
}

int *mult_1_svc(numbers *argp, struct svc_req *rqstp){
	static int result;
	printf("Funcao multiplicacao(%d, %d) foi chamada\n", argp->a, argp->b);
	result = argp->a * argp->b;
	return &result;
}

float *div_1_svc(numbers *argp, struct svc_req *rqstp){
	static float result;
	printf("Funcao divisao(%d, %d) foi chamada\n", argp->a, argp->b);
	result = (float)argp->a / (float)argp->b;
	return &result;
}
